### ISSUE TITLE
Reporting zero correlation when no overlaps found between regions

### ISSUE THREAD

**Issue by esebesty** [favorov/stereogene#2]
Hi,

When the input for stereogene is two region files, where there is no overlap, it simply reports this but does not write out anything into the statistics file.

For example:

regionsA

    chr1    1000    5000
    chr2    1000    5000
    chr3    1000    5000

regionsB

    chr2    6000    8000
    chr3    6000    8000
    chr4    6000    8000

Output is:

    /tmp/association » /bioinf/stereogene-git20180306/StereoGene regionsA.bed regionsB.bed -chrom hg38_genome_size_auto.txt
    Track <regionsA.bed>: no nonZero windows%    

It would be useful to still have a line in the statistics file, with something like a 0 correlation, or NA/nan/etc.

Also, in some cases, I get a segmentation fault, where there is no overlap between the two bed files:

    /tmp/association » /bioinf/stereogene-git20180306/StereoGene regions1_mod_sort.bed regions2_sort.bed -chrom hg38_genome_size_auto.txt
    in1="regions1_mod_sort.bed"
    in2="regions2_sort.bed"
    out="./regions1_mod_sort~regions2_sort"

    bg_cc=-0.006425 
    bg_average=-0.002102

    no non-zero windows pairs
    [1]    25739 segmentation fault (core dumped)  /bioinf/stereogene-git20180306/StereoGene regions1_mod_sort.bed  -chrom

This should be also reported as a 0/NA/nan correlation.

Thanks for the help and the great tool!

Endre

**Comment by favorov** [comment]
Hi Endre,
thanks for the issue. Please, can you send here or to favorov at gmail the files that cause the segfault issue and what system was it?

Thanks, Sasha.

**Comment by esebesty** [comment]
Sent the files in email. The system is Ubuntu 16.04 (kernel 4.4.0-116-generic).

Endre

**Comment by favorov** [comment]
Dear Endre,
thank you for your advices,
we fixed the bug and we added the NA lines to the cumulative files.
