### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by acaprez** [favorov/stereogene#3]
Hello,

I was wondering what license Stereogene is released under. I contribute to the [Bioconda](https://bioconda.github.io/) project, and am interested in adding Stereogene so it can easily be installed using the conda package manager. All contributed packages are required to have a license that allows redistribution however. If you are amenable to this, could you please update the license type to one that allows redistribution? Thanks.

**Comment by favorov** [comment]
Thank you!
We will add a license in a a few days, probably, MIT artistic if it works for Bioconda.

**Comment by acaprez** [comment]
Yes, that will be fine - thanks!

**Comment by favorov** [comment]
Yes, I found it in the StereoGene publication: MIT 2.0 license
Sorry not to add the file, will do it ASAP.

**Comment by favorov** [comment]
There is License.txt in the src folder:
https://github.com/favorov/stereogene/blob/master/src/Licence.txt

**Comment by acaprez** [comment]
Ok great.  Thanks again!
