### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Itagliaf** [favorov/stereogene#4]
Good Morning,

I tried to compile stereogene today (17/09/2019) following the instruction reported in the readme.md

```bash
cd src
make
```

But I get the following error message:

```bash
mkdir -p ./obj
make -f StereoGene.mak
make[1]: Entering directory '/home/ilario/Downloads/stereogene/src'
make[1]: *** No rule to make target 'FourierCorr.cpp', needed by 'obj/FourierCorr.o'.  Stop.
make[1]: Leaving directory '/home/ilario/Downloads/stereogene/src'
Makefile:19: recipe for target 'all' failed
make: *** [all] Error 2
```

And actually there is no file named "fourierCorr.cpp" in the src folder.
Once I renamed fourierCorr.cpp as FourierCorr.cpp, all was compiled soothly.

I'm referring to the master branch (commit https://github.com/favorov/stereogene/commit/7c20cb871cfeb33da43b829ce63f9b37536494c6).

Would it be possible to fix the makefile?

Thank you in advance

Ilario

**Comment by favorov** [comment]
Ilario,
thank you so much!

Sasha

**Comment by favorov** [comment]
Ilario,
thank you again.
The bug is fixed in master branch.

Sasha
